### ISSUE TITLE
 failed to publish events: not connected

### ISSUE THREAD

**Issue by studyhuang1996** [fufuok/beats-http-output#2]
从文件中收集日志同步到 ck 上，使用 http 插件，会报错failed to publish events: not connected 。两边服务器是连的通的，有的数据有过去，有的丢失 。，使用 7.17.7 版本
![image](https://github.com/fufuok/beats-http-output/assets/27665214/f6b15b31-d6f1-4016-913c-3010fd394f26)

**Comment by fufuok** [comment]
filebeat 启动时会加载巨量数据, 对数据接收端冲击很大.
一方面看看接收端压力是不是过大, 造成了部分连接失败. 可以在测试环境准备1万条日志, 单独写个测试的接收端, 验证 filebeat 是否将这1万个数据发送了.

不知道是否直接由 filebeat 发送到 ck 的, 如果是的话是不是批量发送的, ck 对碎片化写入请求不友好.

```yml
output.http:
  hosts: ["http://test-filebeat.ff.cn/bulk"]
  batch_publish: true
  batch_size: 10000
  # compression_level: 1
```

另外有一些专门的 filebeat-clickhouse 插件, 可以尝试一下: https://github.com/codytan/filebeat-clickhouse

------

我们的生产上没有出现上面的情况, 使用的是 7.17.13 版本, 架构是: filebeat -> 汇聚程序 HTTP 接口 -> 后端各 DB
